name: Run Car Launch Workflow

on:
  schedule:
    - cron: '0 6 * * 5' # Every Friday at 6am UTC
  workflow_dispatch: # Allows manual triggering of the action
    inputs:
      email_subject: # Input parameter for the email subject
        description: 'Email subject'
        required: false
        default: 'New Vehicle Data'
      email_body_message:
        description: 'Optional default message text'
        required: false
        default: 'Here are the latest vehicle data!'

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Fetch vehicle data
        run: python scripts/fetch_vehicles.py

      - name: Process data
        run: python scripts/process_data.py

      - name: Email processed data
        run: python scripts/send_email.py
        env: 
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }} # SMTP server
          SMTP_PORT: ${{ secrets.SMTP_PORT }} # Port
          EMAIL: ${{ secrets.EMAIL }} # Your email address
          PASSWORD: ${{ secrets.PASSWORD }} # Your password
          RECIPIENT_EMAIL: daniel.weber4@bluewin.ch # Recipient email address
          EMAIL_SUBJECT: ${{ inputs.email_subject }}
          EMAIL_BODY_MESSAGE: ${{ inputs.email_body_message }}
